active-opacity = 0.930000;
backend = "glx";
frame-opacity = 1.000000;
inactive-opacity = 1.000000;
opacity-rule = [  ];
shadow = true;
shadow-exclude = [  ];
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.750000;
vsync = true;

blur:
{
  method = "dual_kawase";
  strength = 10;
};

rules = (
  { match = "window_type = 'menu'"; shadow = false; blur-background = false; },
  {
    match = "window_type = 'normal'";
    animations = (
      {
        triggers = ["close", "hide"];
        opacity = {
          curve = "linear";
          duration = 0.382;
          start = "window-raw-opacity-before";
          end = 0;
        };
        shadow-opacity = "opacity";
      },
      {
        triggers = ["open", "show"];
        scale-x = {
          curve = "cubic-bezier(0,1.0,1,1)";
          duration = 0.382;
          start = 0;
          end = 1;
        };
        scale-y = "scale-x";
        shadow-scale-x = "scale-x";
        shadow-scale-y = "scale-y";
        offset-x = "(1 - scale-x) / 2 * window-width";
        offset-y = "(1 - scale-y) / 2 * window-height";
        shadow-offset-x = "offset-x";
        shadow-offset-y = "offset-y";
      },
      {
        triggers = ["geometry"]
        scale-x = {
          curve = "cubic-bezier(0,0,0,1)";
          duration = 0.382;
          start = "window-width-before / window-width";
          end = 1;
        }
        scale-y = {
          curve = "cubic-bezier(0,0,0,1)";
          duration = 0.382;
          start = "window-height-before / window-height";
          end = 1;
        }
        offset-x = {
          curve = "cubic-bezier(0,0,0,1)";
          duration = 0.382;
          start = "window-x-before - window-x";
          end = 0;
        }
        offset-y = {
          curve = "cubic-bezier(0,0,0,1)";
          duration = 0.382;
          start = "window-y-before - window-y";
          end = 0;
        }

        shadow-scale-x = "scale-x";
        shadow-scale-y = "scale-y";
        shadow-offset-x = "offset-x";
        shadow-offset-y = "offset-y";
      }
    );
  }
);
